import {generateIdentity,generateArtwork,readPhoto} from './identity.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chapters=[{name:'Idea',purpose:'Understand what is worth making.',tasks:[['identity','Give your idea a face','Choose a first logo direction so the idea has a recognizable identity.','Approve a direction you can build on.'],['brief','Review the idea brief','Make sure the problem, audience and first useful version describe what you mean.','Confirm the brief or record what needs to change.'],['research','Test the biggest assumption','Have a real conversation with someone who has this problem. Record what you heard and what remains uncertain.','Add evidence and make your own assessment of what it supports.']]},{name:'Prototype',purpose:'Try the core experience.',tasks:[['direction','Review the experience direction','The proposed experience starts with your project disk, explains where you are, and presents one meaningful next action.','Decide whether this is the experience you want to test.'],['workflow','Try the complete journey','Ask someone to open a project, explain its purpose, find the next action and return after a decision. Avoid coaching them.','Record what they could do and where they got stuck.']]},{name:'Internal MVP',purpose:'Make it work for real.',tasks:[['engineering','Connect the work to real evidence','The next step is a working connection to the project repository, saved data and automated checks. This preview does not yet verify engineering work.','Repository activity and tests must confirm the implementation.','external']]},{name:'Production',purpose:'Make it dependable.',tasks:[['operate','Verify launch readiness','Confirm deployment, monitoring, recovery and access controls with evidence from the running product.','A live, watched and recoverable product.','external']]},{name:'Learn',purpose:'Learn from people using it.',tasks:[['learn','Listen to the people using it','Collect usage observations and feedback. Identify one useful question to investigate next.','Record a learning and decide what to explore.']]}];
const seed=(id,name,subtitle,problem,audience,stage)=>({id,name,subtitle,problem,audience,context:problem+' '+audience,stage,art:'art/'+id+'.png',done:{},notes:[],history:[],revision:null,auto:false,customArt:false});
let projects=[seed('floppy','Floppy','A home for ideas. A clear way forward.','Help small teams return to an idea and know exactly what to work on next.','Founders and small teams building across tools and conversations.',1),seed('orbit','Orbit','A weekly ritual for finding the signal.','Help a distributed team decide what deserves its attention this week.','Small creative teams with too many open loops.',0),seed('handoff','Handoff','Keep the meaning with the work.','Keep product context intact as work moves from founder to builder.','Founders and technical collaborators.',2)];
let active='floppy',view='library',editId=null,editArt='',editVersion=0,busy=false,saveError='',toastTimer,scrollTimer,lastStored=null;
const generating=new Set();
const STORE='floppy-projects-v2';
try{lastStored=localStorage.getItem(STORE);const saved=JSON.parse(lastStored||'null');if(lastStored!==null){if(!(saved?.version===2&&Array.isArray(saved.projects)&&saved.projects.length&&saved.projects.every(p=>['id','name','subtitle','context','problem','audience','art'].every(k=>typeof p[k]==='string')&&Number.isInteger(p.stage)&&p.stage>=0&&p.stage<5&&Array.isArray(p.notes)&&Array.isArray(p.history)&&p.done&&typeof p.done==='object')))throw Error('Invalid save');projects=saved.projects;active=projects.some(p=>p.id===saved.active)?saved.active:projects[0].id;}}catch{saveError='Saved projects could not be loaded. Changes will not overwrite them.';}
const current=()=>projects.find(p=>p.id===active),task=p=>chapters[p.stage].tasks.find(t=>!p.done[p.stage+':'+t[0]]);
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4500);}
function showSaveError(){let banner=$('saveWarning');if(!banner){banner=document.createElement('p');banner.id='saveWarning';banner.setAttribute('role','alert');document.querySelector('.topbar').after(banner);}banner.textContent=saveError;banner.hidden=!saveError;if($('saveState'))$('saveState').textContent=saveError||'Saved on this device';}
function persist(){if(saveError.startsWith('Saved projects')){showSaveError();return false;}try{if(localStorage.getItem(STORE)!==lastStored){saveError='Another tab changed this collection. Reload to use the latest saved version; edits in this tab are not saved.';showSaveError();return false;}const serialized=JSON.stringify({version:2,projects,active});localStorage.setItem(STORE,serialized);lastStored=serialized;saveError='';showSaveError();return true;}catch{saveError='Not saved: device storage is full or unavailable. Keep this tab open.';showSaveError();toast(saveError);return false;}}
window.addEventListener('storage',e=>{if(e.key===STORE&&e.newValue!==lastStored){saveError='Another tab changed this collection. Reload to use the latest saved version; edits in this tab are not saved.';showSaveError();}});
function event(p,text){p.history.unshift({text,date:new Date().toISOString()});p.history=p.history.slice(0,150);}
function state(p){return p.revision?'Needs changes':task(p)?.[4]==='external'?'Not connected':task(p)?'Your next decision':'Ready for review';}
function disk(p,i){return `<button class="disk-card ${p.id===active?'selected':''}" data-id="${esc(p.id)}" aria-label="Choose ${esc(p.name)}" aria-pressed="${p.id===active}"><div class="disk"><div class="shutter-track"></div><div class="shutter"></div><div class="disk-label"><img src="${esc(p.art)}" alt=""><div class="label-copy"><strong>${esc(p.name)}</strong><span>${String(i+1).padStart(2,'0')}</span></div></div><div class="disk-hole left"></div><div class="disk-hole right"></div></div><span class="disk-number">${esc(chapters[p.stage].name)} / ${esc(state(p))}</span></button>`;}
function library(){ $('carousel').innerHTML=projects.map(disk).join('');$('carousel').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.id,true));resume();}
function resume(){const p=current();$('resumeStage').textContent=chapters[p.stage].name+' · '+state(p);$('resumeTitle').textContent=p.name;$('resumeSubtitle').textContent=p.subtitle;$('resumeNext').textContent='Next: '+(p.revision?'Resolve your review notes':task(p)?.[1]||'Review this chapter');$('diskCount').textContent=String(projects.indexOf(p)+1).padStart(2,'0')+' / '+String(projects.length).padStart(2,'0');}
function select(id,scroll=false){active=id;for(const b of $('carousel').children){b.classList.toggle('selected',b.dataset.id===id);b.setAttribute('aria-pressed',String(b.dataset.id===id));}resume();if(scroll){const b=[...$('carousel').children].find(b=>b.dataset.id===id);$('carousel').scrollTo({left:b.offsetLeft-($('carousel').clientWidth-b.offsetWidth)/2,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}persist();}
function move(n){select(projects[(projects.indexOf(current())+n+projects.length)%projects.length].id,true);}
$('previous').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('carousel').onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1);}};
$('carousel').addEventListener('scroll',()=>{clearTimeout(scrollTimer);if(view!=='library')return;scrollTimer=setTimeout(()=>{if(view!=='library')return;const c=$('carousel'),mid=c.scrollLeft+c.clientWidth/2;let nearest=[...c.children].reduce((a,b)=>Math.abs(b.offsetLeft+b.offsetWidth/2-mid)<Math.abs(a.offsetLeft+a.offsetWidth/2-mid)?b:a);if(nearest&&nearest.dataset.id!==active)select(nearest.dataset.id);},140);});
function open(){clearTimeout(scrollTimer);view='project';$('library').hidden=true;$('project').hidden=false;renderProject();window.scrollTo(0,0);$('projectTitle').focus({preventScroll:true});}
function back(){view='library';$('project').hidden=true;$('library').hidden=false;library();requestAnimationFrame(()=>select(active,true));window.scrollTo(0,0);$('continueProject').focus({preventScroll:true});}
$('continueProject').onclick=open;$('back').onclick=back;document.querySelector('.brand').onclick=e=>{e.preventDefault();back();};
function renderProject(){const p=current(),ch=chapters[p.stage],t=task(p),done=ch.tasks.filter(t=>p.done[p.stage+':'+t[0]]).length;$('projectStage').textContent='Chapter '+String(p.stage+1).padStart(2,'0')+' / '+ch.name+' · '+state(p);$('projectTitle').textContent=p.name;$('projectSubtitle').textContent=p.subtitle;$('projectArt').src=p.art;$('ideaSummary').textContent=p.problem;$('audienceSummary').textContent=p.audience;$('lastActivity').textContent=p.history[0]?.text||'Your context is here. Choose your next direction.';$('saveState').textContent=saveError||'Saved on this device';$('chapterProgress').textContent=done+' of '+ch.tasks.length+' chapter steps confirmed'+(t?' · '+(ch.tasks.length-done)+' remaining':'. Ready for your review.');$('progressFill').style.width=(done/ch.tasks.length*100)+'%';$('chapters').innerHTML=chapters.map((c,i)=>`<button class="chapter ${i===p.stage?'current':i<p.stage?'past':''}" data-chapter="${i}" ${i===p.stage?'aria-current="step"':''}><small>${i===p.stage?'YOU ARE HERE':i<p.stage?'PREVIOUS':'CHAPTER '+String(i+1).padStart(2,'0')}</small>${c.name}</button>`).join('');$('chapters').querySelectorAll('button').forEach(b=>b.onclick=()=>showChapter(+b.dataset.chapter));renderAction(p,t);$('noteCount').textContent=p.notes.length;$('notes').innerHTML=p.notes.map(n=>`<div class="note">${esc(n.text)}<small>Your source material · ${new Date(n.date).toLocaleDateString()}</small></div>`).join('')||'<p class="small">No evidence added yet.</p>';$('history').innerHTML=p.history.map(e=>`<div class="event">${esc(e.text)}<small>${new Date(e.date).toLocaleString()} · recorded on this device</small></div>`).join('')||'<p class="small">Your first decision will start the story.</p>';}
function renderAction(p,t){let html;if(p.revision){html=`<p class="eyebrow">NEXT UP / YOUR REVIEW</p><h2>Make room for a better version.</h2><p class="description">${esc(p.revision)}</p><p class="finish-line"><strong>What moves this forward</strong>Update your direction or record the changes, then return to the decision.</p><div class="action-buttons"><button class="primary" id="revise">Return to review ↗</button><button class="secondary" id="reviseIdentity">Edit identity</button></div>`;}else if(!t){html=`<p class="eyebrow">CHAPTER REVIEW / YOUR DECISION</p><h2>${p.stage===4?'What did you learn?':'Ready for the next chapter?'}</h2><p class="description">You have confirmed the steps in ${chapters[p.stage].name}. Review your notes and unresolved risks before moving forward. These are your judgments, not automated verification.</p><p class="finish-line"><strong>Your next chapter</strong>${p.stage<4?esc(chapters[p.stage+1].purpose):'Keep observing. New learning can become a new idea.'}</p><div class="action-buttons"><button class="primary" id="advance">${p.stage<4?'Begin '+chapters[p.stage+1].name:'Start another learning cycle'} ↗</button><button class="secondary" id="reviewGate">Review requirements</button></div>`;}else{const evidence=['research','workflow','learn'].includes(t[0]);html=`<p class="eyebrow">NEXT UP / ${t[4]==='external'?'AWAITING CONNECTION':'FOR YOU'}</p><h2>${esc(t[1])}</h2><p class="description">${esc(t[2])}</p>${t[0]==='identity'?`<div class="action-art"><span class="logo">${esc(p.name[0]?.toUpperCase())}</span><div><strong>${esc(p.name)}</strong><small>First logo direction · yours to change</small></div></div>`:''}${t[0]==='brief'?`<div class="action-art"><div><strong>${esc(p.name)}</strong><small>${esc(p.context)}</small></div></div>`:''}<p class="finish-line"><strong>What done looks like</strong>${esc(t[3])}</p>${evidence?'<label for="evidenceInput">What happened, and what did you learn?</label><textarea id="evidenceInput" rows="3" maxlength="8000" placeholder="Add your observation and source. Include anything still uncertain."></textarea>':''}<div class="action-buttons">${t[4]==='external'?'<button class="primary" id="connectionInfo">See what needs connecting ↗</button>':`<button class="primary" id="confirm">${evidence?'Save evidence & confirm':t[0]==='identity'?'Use this direction':'Approve direction'} ↗</button><button class="secondary" id="needsWork">Needs more work</button>`}</div>`;}$('actionPanel').innerHTML=html;
if($('confirm'))$('confirm').onclick=()=>{let evidence=$('evidenceInput')?.value.trim();if($('evidenceInput')&&(!evidence||evidence.length<20)){toast('Add a meaningful observation and its source first.');$('evidenceInput').focus();return;}if(evidence)p.notes.unshift({text:evidence,date:new Date().toISOString()});p.done[p.stage+':'+t[0]]=true;event(p,'You confirmed: '+t[1]+'.');persist();renderProject();toast(saveError||'Decision saved. Your next step is ready.');};
if($('needsWork'))$('needsWork').onclick=()=>{p.revision='You asked for another pass on: '+t[1]+'.';event(p,p.revision);persist();renderProject();};if($('revise'))$('revise').onclick=()=>{p.revision=null;event(p,'You reopened the direction for review.');persist();renderProject();};if($('reviseIdentity'))$('reviseIdentity').onclick=edit;
if($('advance'))$('advance').onclick=()=>{if(p.stage<4){p.stage++;event(p,'You chose to begin '+chapters[p.stage].name+'.');}else{delete p.done['4:learn'];event(p,'You started a new learning cycle.');}persist();renderProject();toast(saveError||'A new chapter. Your work came with you.');};if($('reviewGate'))$('reviewGate').onclick=()=>showChapter(p.stage);if($('connectionInfo'))$('connectionInfo').onclick=()=>showChapter(p.stage);}
function showChapter(i){const p=current(),ch=chapters[i];$('chapterDetail').innerHTML=`<h2>${String(i+1).padStart(2,'0')} / ${ch.name}</h2><p class="chapter-description">${ch.purpose} ${i>p.stage?'This is ahead of you. Looking ahead does not change your progress.':''}</p>`+ch.tasks.map(t=>`<div class="requirement"><span>${p.done[i+':'+t[0]]?'✓':'○'}</span><div>${esc(t[1])}<small>${p.done[i+':'+t[0]]?'Confirmed by you':t[4]==='external'?'Not connected · requires external evidence':i<p.stage?'Earlier chapter · not assessed in this preview':'Requires your judgment'}</small><p class="small">${esc(t[3])}</p>${i===p.stage&&p.done[i+':'+t[0]]?`<button class="text-button" data-reopen="${t[0]}">Reopen decision ↗</button>`:''}</div></div>`).join('')+(i>=2&&i<=3?'<p class="small">This local preview cannot connect repositories or verify deployment and tests yet. These requirements remain unconfirmed.</p>':'');$('chapterDetail').querySelectorAll('[data-reopen]').forEach(b=>b.onclick=()=>{const from=ch.tasks.findIndex(t=>t[0]===b.dataset.reopen);ch.tasks.slice(from).forEach(t=>delete p.done[i+':'+t[0]]);p.revision=null;event(p,'You reopened '+ch.tasks[from][1]+'. Later chapter decisions need another review.');persist();$('chapterDialog').close();renderProject();});$('chapterDialog').showModal();}
$('viewRequirements').onclick=()=>showChapter(current().stage);$('noteForm').onsubmit=e=>{e.preventDefault();const text=$('noteInput').value.trim();if(!text)return;current().notes.unshift({text,date:new Date().toISOString()});event(current(),'You added a note to the project.');persist();$('noteInput').value='';renderProject();};
function edit(){const p=current();editId=p.id;editVersion++;editArt=p.art;$('title').value=p.name;$('subtitle').value=p.subtitle;$('context').value=p.context;$('editArt').src=p.art;$('autoDraft').checked=p.auto;$('identityStatus').textContent='';$('photo').value='';$('identityDialog').showModal();}
$('editIdentity').onclick=edit;
function setBusy(value){busy=value;for(const id of ['generateArt','generateCopy','photo'])$(id).disabled=value;$('identityForm').querySelector('[type=submit]').disabled=value;}
async function generate(kind){if(busy)return;const version=editVersion,id=editId,context=$('context').value.trim(),key=$('apiKey').value.trim();setBusy(true);$('identityStatus').textContent=kind==='art'?'Creating your disk artwork…':'Drafting your identity…';try{if(kind==='art'){const art=await generateArtwork({key,context});const blob=await (await fetch(art)).blob();const resized=await readPhoto(blob);if(version===editVersion&&id===editId){editArt=resized;$('editArt').src=editArt;}}else{const draft=await generateIdentity({key,context});if(version===editVersion&&id===editId){$('title').value=draft.title;$('subtitle').value=draft.subtitle;}}if(version===editVersion)$('identityStatus').textContent='Draft ready. Review it, then save.';}catch(e){if(version===editVersion)$('identityStatus').textContent=e.message;}finally{setBusy(false);}}
$('generateArt').onclick=()=>generate('art');$('generateCopy').onclick=()=>generate('copy');$('photo').onchange=async e=>{const file=e.target.files[0],version=editVersion;if(!file)return;setBusy(true);try{const art=await readPhoto(file);if(version===editVersion){editArt=art;$('editArt').src=art;$('identityStatus').textContent='Photo ready. Save to keep it on this disk.';}}catch(e){$('identityStatus').textContent=e.message;}finally{setBusy(false);}};
$('identityForm').onsubmit=async e=>{e.preventDefault();if(busy)return;const p=projects.find(p=>p.id===editId),name=$('title').value.trim(),subtitle=$('subtitle').value.trim();if(!name||!subtitle){$('identityStatus').textContent='Add a title and one-line description.';return;}p.name=name;p.subtitle=subtitle;p.context=$('context').value.trim();p.auto=$('autoDraft').checked;p.customArt=p.customArt||editArt!==p.art;p.art=editArt;event(p,'You updated the project identity.');persist();$('identityDialog').close();renderProject();await autoIdentity(p);};
async function autoIdentity(p){const key=$('apiKey').value.trim(),context=p.context;if(!p.auto||context.length<80||!key||generating.has(p.id))return;const missingCopy=p.subtitle==='An idea taking shape.',missingArt=!p.customArt;if(!missingCopy&&!missingArt)return;generating.add(p.id);toast('Context saved. Drafting the missing identity…');try{if(missingCopy){const draft=await generateIdentity({key,context});if(p.context===context&&p.subtitle==='An idea taking shape.'){p.subtitle=draft.subtitle;event(p,'Google drafted the project description.');}}if(missingArt){const art=await generateArtwork({key,context});const resized=await readPhoto(await(await fetch(art)).blob());if(p.context===context&&!p.customArt){p.art=resized;p.customArt=true;event(p,'Google drafted the disk artwork from your context.');}}persist();if(active===p.id){$('projectArt').src=p.art;$('projectSubtitle').textContent=p.subtitle;if(view==='library'){library();select(active,true);}}toast(saveError||'Your automatic draft is saved. You can edit it anytime.');}catch(err){persist();toast(err.message);}finally{generating.delete(p.id);}}
$('newProject').onclick=()=>{$('newDialog').showModal();};$('newForm').onsubmit=e=>{e.preventDefault();const context=$('newContext').value.trim(),name=$('newName').value.trim();if(!name||context.length<20)return;const p=seed(crypto.randomUUID(),name,'An idea taking shape.',context,'To clarify together.',0);p.art='art/orbit.png';event(p,'You gave this idea a home.');projects.push(p);active=p.id;persist();$('newDialog').close();$('newForm').reset();open();};
library();requestAnimationFrame(()=>select(active,true));if(saveError)toast(saveError);
